import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/topbar";
import Footer from "@/components/footer";
// import logo from "../../public/logo-full-color.svg";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "CTZ",
  description: "Generated by create next app",
  icons: {
    icon: "./logo.jpeg",
  }
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
      </head>
      
      <body>
        <Topbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
